define({
	"root": {
		"Header.HomeView": "Home",
		"Header.CategoriesView": "Categories",
		"Header.ExploreView": "Explore",
		"Header.SearchView": "Search",
		"Header.DetectUserLocation": "Find Me!",
		"Header.Filter": "Change filter...",
		"Header.ScaleTitle.Label": "Start date",
		"Header.ScaleTitle.Minimum": "Earlier",
		"Header.ScaleTitle.Maximum": "Later",
		"AppBar.Commands.Filter": "Filter",
		"AppBar.Commands.Refresh": "Refresh",
		"NumberFormats.Change.NoChange": "NO CHANGE",
		"Proxy.Categories.Music": "Concerts & Tour Dates",
		"Proxy.Categories.Technology": "Technology",
		"Proxy.Categories.Sports": "Sports",
		"Proxy.Categories.Politics_Activism": "Politics & Activism",
		"Proxy.Categories.Movies_Film": "Movies",
		"Proxy.Categories.Conference": "Conferences & Tradeshows",
		"Proxy.Categories.Festivals_Parades": "Festivals",
		"Proxy.Categories.Learning_Education": "Education",
		"Proxy.Categories.Family_Fun_Kids": "Kids & Family",
		"Proxy.Categories.Food": "Food & Wine",
		"Proxy.Categories.Fundraisers": "Fundraising & Charity",
		"Proxy.Categories.Art": "Art Galleries & Exhibits",
		"Proxy.Categories.Support": "Health & Wellness",
		"Proxy.Categories.Books": "Literary & Books",
		"Proxy.Categories.Attractions": "Museums & Attractions",
		"Proxy.Categories.Community": "Neighborhood",
		"Proxy.Categories.Business": "Business & Networking",
		"Proxy.Categories.Singles_Social": "Nightlife & Singles",
		"Proxy.Categories.Schools_Alumni": "University & Alumni",
		"Proxy.Categories.Clubs_Associations": "Organizations & Meetups",
		"Proxy.Categories.Outdoors_Recreation": "Outdoors & Recreation",
		"Proxy.Categories.Performing_Arts": "Performing Arts",
		"Proxy.Categories.Animals": "Pets",
		"Proxy.Categories.Sales": "Sales & Retail",
		"Proxy.Categories.Science": "Science",
		"Proxy.Categories.Religion_Spirituality": "Religion & Spirituality",
		"Proxy.Categories.Other": "Other & Miscellaneous",
		"Proxy.Categories.Endurance": "Endurance",
		"Proxy.Categories.Conventions": "Conventions & Tradeshows",
		"Proxy.Categories.Entertainment": "Entertainments",
		"Proxy.Categories.Travel": "Travel",
		"Proxy.TimePeriods.Today": "Today",
		"Proxy.TimePeriods.This_Week": "This Week",
		"Proxy.TimePeriods.Next_Week": "Next Week",
		"Proxy.TimePeriods.This_Weekend": "This Weekend",
		"Proxy.TimePeriods.This_Month": "This Month",
		"Proxy.TimePeriods.Next_Weekend": "Next Weekend",
		"Proxy.TimePeriods.Next_7_Days": "Next 7 days",
		"Proxy.TimePeriods.Next_14_Days": "Next 14 days",
		"Proxy.TimePeriods.Next_30_Days": "Next 30 days",
		"Proxy.TimePeriods.Next_60_Days": "Next 60 days",
		"Proxy.TimePeriods.Next_Month": "Next Month",
		"Proxy.TimePeriods.Past": "Past",
		"Proxy.TimePeriods.All": "All",
		"Proxy.TimePeriods.Future": "Future",
		"Proxy.TimePeriods.RepeatingEvent": "Repeating event",
		"ErrorMessages.DataCurrentlyIsUnavailable": "Data is unavailable. Please, try again later or change search criteria.",
		"ErrorMessages.DataCurrentlyIsUnavailablePart1": "Data is unavailable. Please, try again later or change ",
		"ErrorMessages.DataCurrentlyIsUnavailablePart2": "search criteria.",
		"ErrorMessages.DataCurrentlyIsUnavailablePart2Title": "Change search criteria",
		"ErrorMessages.YourLocationCannotBeFound":"Your location cannot be found.",
		"ErrorMessages.YourLocationCannotBeFoundChangePermissions":"Your location cannot be found. Change your Permissions to allow Eventy to use your location.",
		"Flyouts.Filter.SubmitLabel": "Apply",
		"DateAndTime.Months.January": "January",
		"DateAndTime.Months.February": "February",
		"DateAndTime.Months.March": "March",
		"DateAndTime.Months.April": "April",
		"DateAndTime.Months.May": "May",
		"DateAndTime.Months.June": "June",
		"DateAndTime.Months.July": "July",
		"DateAndTime.Months.August": "August",
		"DateAndTime.Months.September": "September",
		"DateAndTime.Months.October": "October",
		"DateAndTime.Months.November": "November",
		"DateAndTime.Months.December": "December",
		"DateAndTime.Months.Short.January": "Jan",
		"DateAndTime.Months.Short.February": "Feb",
		"DateAndTime.Months.Short.March": "Mar",
		"DateAndTime.Months.Short.April": "Apr",
		"DateAndTime.Months.Short.May": "May",
		"DateAndTime.Months.Short.June": "Jun",
		"DateAndTime.Months.Short.July": "Jul",
		"DateAndTime.Months.Short.August": "Aug",
		"DateAndTime.Months.Short.September": "Sep",
		"DateAndTime.Months.Short.October": "Oct",
		"DateAndTime.Months.Short.November": "Nov",
		"DateAndTime.Months.Short.December": "Dec",
		"DateAndTime.Days.Monday": "Monday",
		"DateAndTime.Days.Tuesday": "Tuesday",
		"DateAndTime.Days.Wednesday": "Wednesday",
		"DateAndTime.Days.Thursday": "Thursday",
		"DateAndTime.Days.Friday": "Friday",
		"DateAndTime.Days.Saturday": "Saturday",
		"DateAndTime.Days.Sunday": "Sunday",
		"DateAndTime.Days.Short.Monday": "Mon",
		"DateAndTime.Days.Short.Tuesday": "Tue",
		"DateAndTime.Days.Short.Wednesday": "Wed",
		"DateAndTime.Days.Short.Thursday": "Thu",
		"DateAndTime.Days.Short.Friday": "Fri",
		"DateAndTime.Days.Short.Saturday": "Sat",
		"DateAndTime.Days.Short.Sunday": "Sun",
		"Location.Worldwide": "Worldwide",
		"Location.Current": "[Your current location]",
		"Location.DefaultPlaceHolder": "City or town..."
	}
});