define({
	"root": {
		"Header.HomeView": "Home",
		"Header.CategoriesView": "Categories",
		"Header.ExploreView": "Explore",
		"Header.SearchView": "Search",
		"Header.DetectUserLocation": "Find Me!",
		"Header.Filter": "Change filter...",
		"Footer.ContactUs": "Contact Us",
		"AppBar.Commands.Filter": "Filter",
		"AppBar.Commands.Refresh": "Refresh",
		"NumberFormats.Change.NoChange": "NO CHANGE",
		"Proxy.Categories.Music": "Music/Concerts",
		"Proxy.Categories.Technology": "Technology",
		"Proxy.Categories.Sports": "Sporting Events",
		"Proxy.Categories.Politics_Activism": "Politics & Activism",
		"Proxy.Categories.Movies_Film": "Movies/Film",
		"Proxy.Categories.Conference": "Conferences/Seminars",
		"Proxy.Categories.Fairs": "Festivals/Fairs",
		"Proxy.Categories.Seminars": "Classes/Workshops",
		"Proxy.Categories.Family_Fun_Kids": "Kids & Family",
		"Proxy.Categories.Food": "Food/Wine",
		"Proxy.Categories.Fundraisers": "Fundraisers/Charities/Giving",
		"Proxy.Categories.Art": "Art Galleries & Exhibits",
		"Proxy.Categories.Support": "Health & Wellness",
		"Proxy.Categories.Books": "Literary & Books",
		"Proxy.Categories.Comedy": "Comedy",
		"Proxy.Categories.Meetings": "Networking/Clubs/Associations",
		"Proxy.Categories.Business": "Business/Finance/Sales",
		"Proxy.Categories.Social": "Social Events/Mixers",
		"Proxy.Categories.Schools_Alumni": "Schools/Reunions/Alumni",
		"Proxy.Categories.Clubs_Associations": "Organizations & Meetups",
		"Proxy.Categories.Outdoors_Recreation": "Outdoors/Recreation",
		"Proxy.Categories.Performing_Arts": "Performing Arts",
		"Proxy.Categories.Animals": "Pets",
		"Proxy.Categories.Sales": "Sales & Retail",
		"Proxy.Categories.Science": "Science",
		"Proxy.Categories.Religion_Spirituality": "Religion/Spirituality",
		"Proxy.Categories.Other": "Other Events",
		"Proxy.Categories.Endurance": "Endurance",
		"Proxy.Categories.Conventions": "Conventions/Tradeshows/Expos",
		"Proxy.Categories.Entertainment": "Other Entertainment",
		"Proxy.Categories.Travel": "Travel",
		"Proxy.TimePeriods.Today": "Today",
		"Proxy.TimePeriods.This_Week": "This Week",
		"Proxy.TimePeriods.Next_Week": "Next Week",
		"Proxy.TimePeriods.This_Weekend": "This Weekend",
		"Proxy.TimePeriods.This_Month": "This Month",
		"Proxy.TimePeriods.Next_Weekend": "Next Weekend",
		"Proxy.TimePeriods.Next_7_Days": "Next 7 days",
		"Proxy.TimePeriods.Next_14_Days": "Next 14 days",
		"Proxy.TimePeriods.Next_30_Days": "Next 30 days",
		"Proxy.TimePeriods.Next_60_Days": "Next 60 days",
		"Proxy.TimePeriods.Next_Month": "Next Month",
		"Proxy.TimePeriods.Past": "Past",
		"Proxy.TimePeriods.All": "All",
		"Proxy.TimePeriods.Future": "Future",
		"Proxy.TimePeriods.RepeatingEvent": "Repeating event",
		"ErrorMessages.DataCurrentlyIsUnavailable": "Data is unavailable. Please, try again later or change search criteria.",
		"ErrorMessages.DataCurrentlyIsUnavailablePart1": "Data is unavailable. Please, try again later or change ",
		"ErrorMessages.DataCurrentlyIsUnavailablePart2": "search criteria.",
		"ErrorMessages.DataCurrentlyIsUnavailablePart2Title": "Change search criteria",
        "ErrorMessages.YourLocationCannotBeFound":"Your location cannot be found.",
        "ErrorMessages.YourLocationCannotBeFoundChangePermissions":"Your location cannot be found. Change your Permissions to allow EventsHeatMap to use your location.",
		"Flyouts.Filter.SubmitLabel": "Apply",
		"DateAndTime.Months.January": "January",
		"DateAndTime.Months.February": "February",
		"DateAndTime.Months.March": "March",
		"DateAndTime.Months.April": "April",
		"DateAndTime.Months.May": "May",
		"DateAndTime.Months.June": "June",
		"DateAndTime.Months.July": "July",
		"DateAndTime.Months.August": "August",
		"DateAndTime.Months.September": "September",
		"DateAndTime.Months.October": "October",
		"DateAndTime.Months.November": "November",
		"DateAndTime.Months.December": "December",
		"DateAndTime.Months.Short.January": "Jan",
		"DateAndTime.Months.Short.February": "Feb",
		"DateAndTime.Months.Short.March": "Mar",
		"DateAndTime.Months.Short.April": "Apr",
		"DateAndTime.Months.Short.May": "May",
		"DateAndTime.Months.Short.June": "Jun",
		"DateAndTime.Months.Short.July": "Jul",
		"DateAndTime.Months.Short.August": "Aug",
		"DateAndTime.Months.Short.September": "Sep",
		"DateAndTime.Months.Short.October": "Oct",
		"DateAndTime.Months.Short.November": "Nov",
		"DateAndTime.Months.Short.December": "Dec",
		"DateAndTime.Days.Monday": "Monday",
		"DateAndTime.Days.Tuesday": "Tuesday",
		"DateAndTime.Days.Wednesday": "Wednesday",
		"DateAndTime.Days.Thursday": "Thursday",
		"DateAndTime.Days.Friday": "Friday",
		"DateAndTime.Days.Saturday": "Saturday",
		"DateAndTime.Days.Sunday": "Sunday",
		"DateAndTime.Days.Short.Monday": "Mon",
		"DateAndTime.Days.Short.Tuesday": "Tue",
		"DateAndTime.Days.Short.Wednesday": "Wed",
		"DateAndTime.Days.Short.Thursday": "Thu",
		"DateAndTime.Days.Short.Friday": "Fri",
		"DateAndTime.Days.Short.Saturday": "Sat",
		"DateAndTime.Days.Short.Sunday": "Sun",
        "Location.Worldwide": "Worldwide"
	}
});